### ISSUE TITLE
General help / Conversation 

### ISSUE THREAD

**Issue by colincowie** [colincowie/SupremeAutoPurchase#4]

**Comment by colincowie** [comment]
@kaaetech I'm not really sure, however I might try testing some things to figure out

**Comment by PriorKibbles** [comment]
@colincowie @kaaetech Is the original one (Colin's) faster for one item or is kaaetech's fork? Usually, how long do you think it'll take for the entire checkout process. Is there anyway to check. My download speed is 117 Mbps and my upload is 11.74 Mbps. I am currently running on a 2015 Macbook Pro with a 2.7 GHz Intel Core i5 with 8 GBs of ram. I was just curious to see if this is swift enough for something like a box logo.

**Comment by kaaetech** [comment]
You would checkout in between 2 and 4 seconds depending on a lot of variables like supremes website speed, your internet speed, your computer speed, location, item amount

Sent using the mail.com mail app

**Comment by colincowie** [comment]
@PriorKibbles @kaaetech in my most recent build it will tell you how fast it is. PhantomJS is about a second slower on the first run. On my Macbook Pro with 2.4 GHz Intel Core i5 and 8 GBs of ram the fastest I've seen was 3.02 seconds, the average for me is 4.4 seconds.

**Comment by kaaetech** [comment]
Okay so PhantomJS first run is slow, thats a thing

Sent using the mail.com mail app

**Comment by colincowie** [comment]
Yeah, I've tested it a lot, but it's possible that its just my system

**Comment by kaaetech** [comment]
i guess so, my Macbook is the same shit all time. chrome is faster.

Sent using the mail.com mail app

**Comment by colincowie** [comment]
Just curious, have you tried using phantomJS on your system? If so, what kind of times are you getting?

**Comment by kaaetech** [comment]
4-5 seconds on my Macbook

Sent using the mail.com mail app

**Comment by kaaetech** [comment]
I can't get Firefox to work on Mac and therefore not the nopictures version

Sent using the mail.com mail app

**Comment by colincowie** [comment]
Do you run chrome with no images?
I'm getting 4-5 seconds using chrome with images

**Comment by colincowie** [comment]
Update: I used 
    `chromeOptions = webdriver.ChromeOptions()
    prefs = {"profile.managed_default_content_settings.images":2}
    chromeOptions.add_experimental_option("prefs",prefs)
    driver = webdriver.Chrome(chrome_options=chromeOptions)`
To run with out images, but I'm still looking at 4 - 5 seconds speed

**Comment by kaaetech** [comment]
we'll on the checkout page its slow and fills - a field at once. we need that done faster

Sent using the mail.com mail app

**Comment by Hezion** [comment]
@colincowie yes, but that is with cold images that are in the CDNs for at least a week. After the drop the cache invalidation of the CDN is taking place. Thats why it is important imho to block loading images.

**Comment by colincowie** [comment]
I just got a couple runs in 1.6 seconds! I did it with phantom running before use with  `phantomjs --webdriver=8910` and change the code to `driver = webdriver.PhantomJS(port=8910, service_args=['--load-images=no'])`

**Comment by PriorKibbles** [comment]
@colincowie what driver do you recommend? Firefox or phantomJS? If PhantomJS, how can I get that?

**Comment by colincowie** [comment]
@PriorKibbles I would recommend phantomJS. If you are using a mac and have homebrew install, its just `brew install phantomjs`

**Comment by kaaetech** [comment]
i did
browser = webdriver.PhantomJS(port=8910, service_args=['--load-images=no'])

and got. AttributeError: 'WebDriver' object has no attribute 'visit'

**Comment by kaaetech** [comment]
nevermind got it working
selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with xpath '//*[@id=\"cart-cc\"]/fieldset/p[2]/label/div/ins'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity

now this?

**Comment by colincowie** [comment]
That is to select the "I read terms and policy box......" But for some reason its not found for you

**Comment by kaaetech** [comment]
Yeah its something whole different.

**Comment by kaaetech** [comment]
order-terms i guess

**Comment by colincowie** [comment]
Change
 `driver.find_element_by_xpath('//*[@id="cart-cc"]/fieldset/p[2]/label/div/ins').click()`
to
`driver.find_element_by_xpath('//*[@id="cart-cc"]/fieldset/p/label/div/ins')`

**Comment by kaaetech** [comment]
Okay sure, I've run it 10 times now and gets between 4 and 4.3 seconds on my Desktop workstation

**Comment by kaaetech** [comment]
For me using chrome is half a second, to a whole faster.

**Comment by colincowie** [comment]
Did you have `phantomjs --webdriver 8910` running in a different terminal before use?

**Comment by kaaetech** [comment]
of course :)

Sent using the mail.com mail app

**Comment by colincowie** [comment]
Nice! I would keep using chrome then. for me chrome is a lot slower on my Mac. I think a lot of it situational to each computer, thus making it hard to benchmark speed

**Comment by kaaetech** [comment]
What is the colorway names for the TNF nupste?

Sent using the mail.com mail app

**Comment by PriorKibbles** [comment]
@kaaetech @colincowie how do you guys test your times without buying things?

**Comment by PriorKibbles** [comment]
@kaaetech @colincowie also I am now trying to run the _phantomjs_ version. Do I need to download anything else or no? I already have downloaded the driver in my terminal because I already had homebrew.

**Comment by colincowie** [comment]
Commenting out the commit line or entering incorrect CVC info. I believe just the driver and that stuff you probably already have from install.sh

**Comment by PriorKibbles** [comment]
So everything else should be correct except the CVC? or can credit card number be incorrect but also where do I view this timer?

**Comment by colincowie** [comment]
Any incorrect credit card information will prevent yourself from getting charged, it should still be in the right format though to prevent errors. The timer is built in with my newest update, it'll print out the time in seconds in your terminal

**Comment by PriorKibbles** [comment]
It keeps saying that is moving on to the next stage of purchase but is not doing anything.

**Comment by colincowie** [comment]
That means that the phantomJS webdriver is not set up properly

**Comment by PriorKibbles** [comment]
what should i do? I installed it already by typing _brew install js_ into my terminal.

**Comment by colincowie** [comment]
did you mean brew install phantomjs ? Did it properly install? Test it by typing phantomjs in a terminal

**Comment by PriorKibbles** [comment]
yeah i meant phantomjs sorry. when i typed it in it displays: "phantomjs>"

**Comment by colincowie** [comment]
Is your buy.py file the most recent update version?

**Comment by PriorKibbles** [comment]
yes sir

**Comment by colincowie** [comment]
hmmmmm, Can you post a screen shot?

**Comment by PriorKibbles** [comment]
http://imgur.com/a/7DGAm sorry it took so long. I got out of school and forgot.

**Comment by colincowie** [comment]
It's all good, the issue that your having is the `SelectOption:` from the config is set to 1, however the jacket you are testing with has no option 1, try using `SelectOption:Large` instead!

**Comment by PriorKibbles** [comment]
http://imgur.com/a/bNxuP I put large instead now. Still getting some sort of error and no time shown?

**Comment by colincowie** [comment]
maybe try changing it to `SelectOption:Large` instead of `SelectOption: Large` also check the website and see if they still have large in stock. The time only shows once the code has finished running properly with out errors

**Comment by PriorKibbles** [comment]
I did and it is in stock. Still error

**Comment by colincowie** [comment]
Same error?

**Comment by PriorKibbles** [comment]
yeah

**Comment by PriorKibbles** [comment]
but yeah I've tried everything and its still giving me this error. Please help :(

**Comment by olipreme666** [comment]
same problem for me ^

**Comment by kaaetech** [comment]
C:\Users\****************************************************>phantomjs --webdriver 8910
[ERROR - 2016-11-16T15:39:28.517Z] GhostDriver - main.fail - {"line":85,"sourceURL":"phantomjs://code/main.js","stack":"global code@phantomjs://code/main.js:85:56"}

  phantomjs://platform/console++.js:263 in error


-
facing this with phantomjs now, didnt yesterday. weird

**Comment by colincowie** [comment]
@olipreme666 @PriorKibbles Sorry for the delay, I had an bug in the way that I was selecting from that drop down. I just pushed out the new update that fixed it!

**Comment by colincowie** [comment]
@kaaetech I'm 90% sure that means phantomJS is still running on port 8910. I would check your task manager for PhantomJS and stop it then try it again, that worked for me

**Comment by kaaetech** [comment]
oh you were right.
3.92696441483 Seconds with phantomjs (avg. on 5 tries)
3 seconds with chrome and my fork :D 

weird right?

**Comment by kaaetech** [comment]
actually just hit --- 2.98900008202 sekunder --- with mine which is under 3, i will buy a high performance server close to supremes location and run it on there and maybe get even faster.

**Comment by colincowie** [comment]
Nice! What location would be that?

**Comment by olipreme666** [comment]
The update worked fine but I tried to buy socks and did not get an email or anything from supreme about the order. Is it a Ghost order?

**Comment by colincowie** [comment]
@olipreme666 Most likely that means something went wrong in the checkout form, im looking into right now

**Comment by kaaetech** [comment]
@olipreme666 did you use, your own Credit Card? Our just the blank included one?

**Comment by olipreme666** [comment]
@kaaetech I used my own. Just want to test it.

**Comment by kaaetech** [comment]
Just make a sleep in the end, and see if it suceeds. Did they charge you?

**Comment by colincowie** [comment]
It's an issue with the submit but going a milisecond  before clicked accepted terms, I fixed it by changing the Xpath i'm selecting from but i'm working on a way of it showing form errors

**Comment by kaaetech** [comment]
Just print them in the console @colincowie, or make 0.1 seconds sleep before checking out.

**Comment by olipreme666** [comment]
Nope, they didn't charge for it

**Comment by kaaetech** [comment]
Then there was clearly a error. Make some sleeps/waits after forms getting filled and try again :)

**Comment by kaaetech** [comment]
You can then check where is the error, or if its a ghost order. @olipreme666

**Comment by colincowie** [comment]
@kaaetech @olipreme666 I just pushed an updated that detects if the payment or address information goes wrong.

**Comment by kaaetech** [comment]
Thats cool, I have no need for it but glad that you are so fasting helping @olipreme666 .

**Comment by colincowie** [comment]
@kaaetech is your fork using selenium?

**Comment by olipreme666** [comment]
thanks so much @colincowie  @kaaetech i will test out with buying the sock later today. But do you think after check out that the script will display the order number after the success page check out?

**Comment by colincowie** [comment]
@olipreme666 I'll try too implement that soon. There currently a bug with the selenium randomly sending keys incorrectly that I'm looking into

**Comment by kaaetech** [comment]
Connor for your version please implement "city" for non US users, just like mine has.

**Comment by DAN13L6** [comment]
Is this a scam? why would you release it for free?

**Comment by DAN13L6** [comment]
seems too good to be true, especially in spite of the tnf drop tommorow

**Comment by colincowie** [comment]
@DAN13L6 no I've been working on this project for a while, there is still a couple different bugs with the PhantomJs version. However the firefox branch will be updated with a completely working build by 11 or 12 pm EST today

**Comment by DAN13L6** [comment]
do you have it available for free for like testing purposes or something ?

**Comment by colincowie** [comment]
@DAN13L6 Yep.... one day when it's perfected i'll make it private

**Comment by colincowie** [comment]
@kaaetech Done, city option added.

**Comment by DAN13L6** [comment]
sounds cool, could you possibly make a noobproof guide? like i got lost at the "sh install sh" part, i downloaded the programs mentioned (python and phantomJS)

**Comment by colincowie** [comment]
@DAN13L6 Yeah, I'll release and in depth guide to usage tonight

**Comment by DAN13L6** [comment]
sounds great, does this work on the uk site? and when you say tonight, in how many hours would that be aproximately, ( i think we're in completely different timezones)

**Comment by colincowie** [comment]
@DAN13L6 It should, and probably 9 or 10 hours

**Comment by DAN13L6** [comment]
thats like 5am here, great lol

**Comment by PriorKibbles** [comment]
since you are getting consistent fast speeds @kaaetech what do I  need for your fork? I already have python 2.7. Do I need any different drivers?

**Comment by kaaetech** [comment]
@PriorKibbles You will need Chromedriver in the path of the bot if you are on Windows and chromedriver in the /usr/local/bin if you are on a macintosh. I guess the same dependencies as in requirements.txt and so on.. I guess the errors will guide you tbh

**Comment by PriorKibbles** [comment]
@kaaetech sorry if this is dumb. How do I download a chromedriver

**Comment by PriorKibbles** [comment]
btw @colincowie your current phantomjs one has no city field.

**Comment by kaaetech** [comment]
@PriorKibbles https://chromedriver.storage.googleapis.com/index.html?path=2.25/
I'm heading off to bed.
Just add City: 
to the config, its in the code. It will work. Good night sleep well fokes. +1

**Comment by kaaetech** [comment]
@colincowie for your version with status printing, it says shit about the creditcard which aint true like number invalid or brand not matching :D

**Comment by PriorKibbles** [comment]
getting another error   
File "buy.py", line 21, in <module>
    product_name2 =  config.get('produkt', 'keyword2')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'keyword2' in section: 'produkt'

http://imgur.com/a/LW82O

**Comment by kaaetech** [comment]
@PriorKibbles you deleted something in the config? 
keyword2 has been deleted?

**Comment by PriorKibbles** [comment]
yeah i thought if I only wanted one item delete that. my bad.

**Comment by kaaetech** [comment]
look what i wrote in buy.py at the am variable.
am = 2 # mode 2 will purchase keyword2 in the size2, and color2. mode1 will purchase both keyword2 and keyword.

**Comment by colincowie** [comment]
@kaaetech see that's what I thought and I did some research with screen shots and I discovered that the function `.send_keys(ccnum)` was running too fast and entering the info all scrambled. The same thing was happening in chrome for me. It's an issue with selenium. I solved it by using `.click()` on that element before sending the keys. I'm away from my computer right now but I'll send an update with that fixed soon.

**Comment by PriorKibbles** [comment]
@kaaetech also receiving this http://imgur.com/a/ae7qX

**Comment by kaaetech** [comment]
just remove this on line 65 " print(r)"

**Comment by kaaetech** [comment]
@PriorKibbles

**Comment by DAN13L6** [comment]
can you actually use this right now to buy supreme items at drop? and if not, do you think it will be usable, before 11am london time tommorow?

**Comment by kaaetech** [comment]
@DAN13L6 of course, we are just improving. its been useable for atleast 14 days :)

kind regards and good night

**Comment by nmsfabio** [comment]
@colincowie thanks for this especially for free.  Is it only compatible with python 2.7 or am i fine with 3.5

**Comment by olipreme666** [comment]
everything works! checked out the socks and went thru. Thank you for this script.

**Comment by PriorKibbles** [comment]
@olipreme666 which one are you using? chromefork, mozilla, or phantomjs?

**Comment by olipreme666** [comment]
phantomjs. It takes 10 second to check out. Is there a way to get a better time? @PriorKibbles

**Comment by PriorKibbles** [comment]
Yeah phantomjs is kinda slow for me too but i'm pretty sure thats the best one from colin. I wanted to try the chromedriver fork but its not working for me so i can't test those times. @colincowie I keep getting this error now too even though it worked earlier. http://imgur.com/a/RQimU

**Comment by colincowie** [comment]
@nmsfabio glad I could help, I'm not sure, it should though. Try it out and let me know

**Comment by colincowie** [comment]
Changing to chrome is only one different line of code! driver = webdriver.Chrome()

I'm gonna make a branch tonight

**Comment by PriorKibbles** [comment]
can you help me real quick? why is this occurring http://imgur.com/a/RQimU even though it worked fine for me earlier?

**Comment by colincowie** [comment]
@olipreme666 I'm happy it worked for you! running `phantomjs --8910` in another terminal before hand will make it much faster however every system is different. Defiantly try out chrome and Firefox

**Comment by colincowie** [comment]
You're missing the `import time` line at the top of the program with the other imports

**Comment by PriorKibbles** [comment]
how can i fix that

**Comment by colincowie** [comment]
The second line of the buy.py should be import time

**Comment by PriorKibbles** [comment]
it is? http://imgur.com/a/onyxT

**Comment by olipreme666** [comment]
Do I use the console in page inspect to use the script on chrome?

**Comment by PriorKibbles** [comment]
@colincowie okay thanks. Can you fix that on yours then? I just downloaded it and it was like that. Also why is it displaying that it cant find items now? Idk what happened but its not working anymore even though i tried it this morning and it went thru fine

**Comment by colincowie** [comment]
@PriorKibbles is has been fixed on mine, if you check buy.py you'll see it, double check the config to make sure you got the right keywords. 

@olipreme666 nah it's the same script but it just will open a chrome browser. I'll push a branch for it in a couple hours

**Comment by PriorKibbles** [comment]
Oh oops I accidentally downloaded the branches instead of the master one. Also, it keeps saying product not found?

**Comment by olipreme666** [comment]
oh is it a google driver file that i put in the folder? @colincowie

**Comment by colincowie** [comment]
@PriorKibbles That just means that your keywords, category and color aren't matching any product.

@olipreme666 [You need to install chrome webdrivers for selenium](https://sites.google.com/a/chromium.org/chromedriver/downloads)

**Comment by nmsfabio** [comment]
update to python 3.x compatibility.  i dont think it will work as ConfigParser has been renamed to configparser. tried just rewriting it but that didnt seem to solve. any ideas?

**Comment by colincowie** [comment]
What was the error? @nmsfabio

**Comment by nmsfabio** [comment]
![cp](https://cloud.githubusercontent.com/assets/23172289/20373399/ac54e432-ac3f-11e6-9a92-d8335070a66c.PNG)
![cp1](https://cloud.githubusercontent.com/assets/23172289/20373400/ac56899a-ac3f-11e6-9c50-1610fe2779c5.PNG)

**Comment by nmsfabio** [comment]
top one is it being left as import ConfigParser
bottom is it being changed to import configparser

**Comment by nmsfabio** [comment]
im semi new to python and code in general; so i may be wrong here.  I dont know if the install.sh file would have any affect on this as im not able to get that running (i have cygwin with curl but still not working properly).

**Comment by colincowie** [comment]
@nmsfabio The install.sh is just an easy way to install the requirements in requirements.txt

You have to change line 12 to `Config = configparser.ConfigParser()`

**Comment by nmsfabio** [comment]
@colincowie alright thanks man.  believe i got it running with that change.  and instead of using the sh command i just ran "pip3 install -r requirements.txt" and it seemed to work too.  thanks again

**Comment by colincowie** [comment]
Glad to help!

**Comment by colincowie** [comment]
Closing this thread as it's getting very long

**Comment by DAN13L6** [comment]
When is that noob proof Guide coming up ?
